spring:
  application:
    name: MeghanaStore
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  api-docs:
    path: /api-docs
